### ISSUE TITLE
No visible "Shared with me" subfolder

### ISSUE THREAD

**Issue by kridency** [prrvchr/gDriveOOo#16]
No visible "Shared with me" subfolder if you navigate through Google Drive under LibreOffice dialog.

**Comment by prrvchr** [comment]
Hi biofreak,

Yes it's normal nothing is implemented concerning shared drives.

In addition, Google is forcing us to migrate the scopes used for **gDriveOOo**.
I will switch from `https://www.googleapis.com/auth/drive` to `https://www.googleapis.com/auth/drive.file` since the use of the `https://www.googleapis.com/auth/drive` scope has become chargeable. Thanks Google...

Tests have been conducted with the next version 1.1.6 and this new scope will be used in version 1.2.0.

~~Therefore, if we use this new scope, it will not be possible to access the shared drives since this scope does not allow it. Shame...~~

**Comment by kridency** [comment]
Hi, prrvchr!

Thanks for your fast reply.
What you describe it is something discouraging.
Suspect that for the same reason there are no shortcuts visible while you navigate through root.

**Comment by prrvchr** [comment]
Hi biofreak,

Just to tell you that finally I managed to implement shared folders. You have to use the latest version 1.1.6. Enjoy.
